// Representative business scenarios, not claims about personal client engagements.
export const attackContent = {
  en: {
    attackLabel: 'FIVE COMMON ATTACK PATTERNS', attackHint: 'Explore a business risk', caseLabel: 'REPRESENTATIVE SCENARIO', impactLabel: 'Business impact', responseLabel: 'Response & recovery', caseAction: 'Discuss this risk', sourcesLabel: 'Guidance & incident data',
    attacks: [
      {title:'Phishing & payment fraud', short:'A “supplier” changes bank details.', problem:'Finance receives a convincing email asking to change a supplier’s bank account. A payment goes to the attacker.', impact:'Lost funds, delayed supplier payments and an urgent cash-flow problem.', response:'Contact the bank immediately, preserve the email and secure affected accounts. Verify payment changes by calling a known number; introduce dual approval and email authentication.', source:0},
      {title:'Ransomware', short:'Systems locked. Work stops.', problem:'Malware encrypts shared files and business systems. Staff cannot process orders or access documents.', impact:'Operations stop; revenue, deadlines and customer trust are at risk.', response:'Isolate affected systems, investigate the entry point and restore clean systems from verified offline or immutable backups. Add endpoint detection, segmentation and rehearsed recovery.', source:1},
      {title:'Stolen credentials', short:'Someone else has your cloud login.', problem:'An attacker signs in with a stolen password, reads company email and accesses shared cloud files.', impact:'Confidential data can leak; invoices and messages can be manipulated.', response:'Revoke sessions and tokens, reset credentials and review access logs. Use phishing-resistant MFA, least privilege and alerts for unusual sign-ins.', source:2},
      {title:'Unpatched vulnerabilities', short:'An exposed VPN becomes an entry point.', problem:'A known flaw in an internet-facing VPN or business application lets an attacker enter the network.', impact:'Unauthorized access, data theft and possible disruption of critical systems.', response:'Restrict access, investigate compromise, patch or replace the affected product and rotate exposed credentials. Maintain an asset inventory and prioritize exploited vulnerabilities.', source:3},
      {title:'Supplier compromise', short:'A trusted connection carries the breach.', problem:'A supplier’s account or remote support tool is compromised. Its trusted connection gives the attacker access to your systems.', impact:'A partner’s incident becomes your downtime or data breach.', response:'Suspend affected connections, coordinate containment and verify systems before restoring access. Limit supplier permissions, monitor access and agree on incident-notification duties.', source:4}
    ]
  },
  ru: {
    attackLabel:'ПЯТЬ РАСПРОСТРАНЁННЫХ КИБЕРУГРОЗ', attackHint:'Посмотрите, как это влияет на бизнес', caseLabel:'ТИПОВОЙ СЦЕНАРИЙ', impactLabel:'Последствия для бизнеса', responseLabel:'Как устранить последствия и снизить риск', caseAction:'Обсудить защиту', sourcesLabel:'Рекомендации и данные об инцидентах',
    attacks:[
      {title:'Фишинг и подмена реквизитов',short:'«Поставщик» просит оплатить на новый счёт.',problem:'Бухгалтерия получает убедительное письмо об изменении банковских реквизитов поставщика. Деньги уходят мошенникам.',impact:'Потеря денег, задержка расчётов с поставщиком и кассовый разрыв.',response:'Срочно связаться с банком, сохранить письмо и защитить затронутые учётные записи. Проверять смену реквизитов по известному номеру телефона, ввести двойное согласование платежей и защиту почтового домена.',source:0},
      {title:'Атака шифровальщика',short:'Файлы заблокированы. Работа остановлена.',problem:'Вредоносная программа шифрует общие файлы и корпоративные системы. Сотрудники не могут обрабатывать заказы и работать с документами.',impact:'Простой, потеря выручки, срыв сроков и ущерб репутации.',response:'Изолировать заражённые устройства, установить причину проникновения и восстановить системы из проверенных автономных или неизменяемых резервных копий. Внедрить EDR, сегментацию сети и регулярно проверять восстановление.',source:1},
      {title:'Кража учётных данных',short:'Посторонний получил доступ к вашему облаку.',problem:'Злоумышленник входит по украденному паролю, читает корпоративную почту и получает доступ к облачным документам.',impact:'Утечка конфиденциальных данных, подмена писем и счетов на оплату.',response:'Завершить активные сеансы, отозвать токены, сменить пароли и проверить журналы доступа. Настроить устойчивую к фишингу многофакторную аутентификацию, минимальные права и оповещения о подозрительных входах.',source:2},
      {title:'Эксплуатация уязвимостей',short:'Необновлённый VPN открывает доступ в сеть.',problem:'Через известную уязвимость в доступном из интернета VPN или приложении атакующий проникает в сеть компании.',impact:'Несанкционированный доступ, кража данных и риск остановки критических систем.',response:'Ограничить доступ, проверить признаки взлома, обновить или заменить уязвимый продукт и сменить скомпрометированные учётные данные. Вести учёт IT-активов и в первую очередь устранять уязвимости, уже используемые в атаках.',source:3},
      {title:'Атака через поставщика',short:'Взлом партнёра затрагивает вашу компанию.',problem:'Злоумышленник взламывает учётную запись подрядчика или средство удалённой поддержки и использует доверенный доступ к вашим системам.',impact:'Инцидент у партнёра приводит к простою или утечке данных у вас.',response:'Отключить затронутые подключения, согласовать действия с поставщиком и проверить системы перед восстановлением доступа. Ограничить права подрядчиков, контролировать подключения и закрепить порядок уведомления об инцидентах.',source:4}
    ]
  },
  he: {
    attackLabel:'חמישה דפוסי תקיפה נפוצים', attackHint:'גלו את הסיכון לעסק', caseLabel:'תרחיש לדוגמה', impactLabel:'ההשפעה על העסק', responseLabel:'טיפול, התאוששות ומניעה', caseAction:'נדבר על הגנה על העסק', sourcesLabel:'הנחיות ומאגרי אירועים',
    attacks:[
      {title:'דיוג והונאת תשלומים',short:'״הספק״ מבקש להעביר כסף לחשבון חדש.',problem:'הנהלת החשבונות מקבלת הודעה משכנעת על שינוי פרטי הבנק של ספק. התשלום מועבר לחשבון של התוקף.',impact:'אובדן כספי, עיכוב בתשלום לספק ופגיעה בתזרים המזומנים.',response:'לפנות מיד לבנק, לשמור את ההודעה ולאבטח את החשבונות שנפגעו. לאמת שינוי פרטי תשלום בשיחה למספר מוכר, לדרוש אישור כפול ולהגדיר אימות לדומיין הדואר.',source:0},
      {title:'מתקפת כופרה',short:'הקבצים נעולים. העבודה נעצרת.',problem:'נוזקה מצפינה קבצים משותפים ומערכות עסקיות. העובדים אינם יכולים לטפל בהזמנות או לגשת למסמכים.',impact:'השבתת פעילות, אובדן הכנסות, עיכובים ופגיעה באמון הלקוחות.',response:'לבודד מערכות שנפגעו, לבדוק את מקור החדירה ולשחזר סביבה נקייה מגיבויים מנותקים או בלתי ניתנים לשינוי שנבדקו מראש. להוסיף הגנת תחנות קצה, הפרדת רשתות ותרגול התאוששות.',source:1},
      {title:'גניבת פרטי התחברות',short:'גורם זר נכנס לחשבון הענן שלכם.',problem:'תוקף משתמש בסיסמה גנובה כדי לקרוא דואר ארגוני ולגשת למסמכים בענן.',impact:'דליפת מידע רגיש, שינוי הודעות והונאות באמצעות חשבוניות.',response:'לבטל חיבורים פעילים ואסימוני גישה, להחליף סיסמאות ולבדוק יומני גישה. להפעיל אימות רב־גורמי עמיד בפני דיוג, לצמצם הרשאות ולהתריע על כניסות חריגות.',source:2},
      {title:'ניצול חולשות אבטחה',short:'רכיב VPN שלא עודכן פותח דלת לרשת.',problem:'חולשה מוכרת ברכיב VPN או ביישום החשוף לאינטרנט מאפשרת לתוקף לחדור לרשת הארגונית.',impact:'גישה בלתי מורשית, גניבת מידע וסיכון להשבתת מערכות קריטיות.',response:'להגביל גישה, לבדוק סימני חדירה, לעדכן או להחליף את הרכיב ולשנות פרטי התחברות שנחשפו. לנהל מלאי נכסי IT ולתעדף חולשות שכבר מנוצלות בתקיפות.',source:3},
      {title:'תקיפה דרך ספק',short:'אירוע אצל הספק מגיע למערכות שלכם.',problem:'חשבון של ספק או כלי תמיכה מרחוק נפרץ. התוקף מנצל את הגישה המורשית כדי להגיע למערכות הארגון.',impact:'אירוע אצל שותף הופך להשבתה או לדליפת מידע אצלכם.',response:'להשעות חיבורים שנפגעו, לתאם בלימה עם הספק ולבדוק את המערכות לפני חידוש הגישה. לצמצם הרשאות ספקים, לנטר גישה ולהגדיר חובת דיווח על אירועים.',source:4}
    ]
  }
};
export const attackSources = [
  {label:'CISA · Email protection',url:'https://github.com/cisagov/ScubaGear/blob/main/PowerShell/ScubaGear/baselines/exo.md'},
  {label:'CISA · Endpoint protection',url:'https://github.com/cisagov/ScubaGear/blob/main/PowerShell/ScubaGear/baselines/defender.md'},
  {label:'CISA · Identity protection',url:'https://github.com/cisagov/ScubaGear/blob/main/PowerShell/ScubaGear/baselines/aad.md'},
  {label:'CISA · Known Exploited Vulnerabilities',url:'https://github.com/cisagov/kev-data'},
  {label:'VERIS · Public incident database',url:'https://github.com/vz-risk/VCDB'}
];
