import { mailCopy } from './mail-copy.js';
import { hebrewContent } from './hebrew.js';
import { attackContent } from './attacks.js';
import { editorial } from './localization.js';
export const content = {
  en: {
    name: 'Sergey Shlomov', nav: ['Expertise', 'Experience', 'About', 'Contact'], talk: 'Let’s talk', menu: 'Open menu', close: 'Close',
    eyebrow: 'CYBERSECURITY. TECHNOLOGY. LEADERSHIP.', headline: ['Your business.', 'My mission.'], accent: 'Secure by design.',
    intro: 'Turning complex technology and cyber risks into clear decisions. Enterprise experience. A strategic mindset. A partner you can trust.',
    cta: 'Secure your next move', explore: 'Explore my expertise', location: 'BASED IN ISRAEL · WORKING GLOBALLY', scroll: 'SCROLL TO EXPLORE',
    scenario: 'OPERATIONS ROOM / INTERACTIVE SCENE', scenarioNote: 'Illustrative visualization', hotspots: ['Cyber defense', 'IT strategy', 'Incident readiness'], pagerLabel: 'A MESSAGE WORTH READING', pager: 'YOU MAY BE AT RISK. EXTREMIST & STATE-SPONSORED HACKERS NEVER WAIT. PROTECT WHAT MATTERS.', pagerHint: 'Tap to read the briefing',
    trust: 'EXPERIENCE BUILT IN COMPLEX ENVIRONMENTS', gov: 'Ministry of Finance', military: 'IDF · MAMRAM',
    expertiseLabel: '01 / HOW I CAN HELP', expertiseTitle: 'One partner.\nA stronger organization.', expertiseIntro: 'From the boardroom to your technology stack. Practical leadership that connects security, systems and business outcomes.',
    services: [
      {title: 'Cybersecurity & CISO advisory', tag: 'PROTECT WHAT MATTERS', desc: 'Understand your exposure. Build a security roadmap. Make informed decisions before an incident makes them for you.', bullets: ['Cyber risk assessment & gap analysis', 'Security governance, privacy & third-party risk', 'Incident response governance & business continuity'], detail: 'An independent view of your security posture, with a practical plan prioritized by business impact. I coordinate security reviews, specialist testing and remediation with your teams and vendors.', output: 'A prioritized risk register, ownership model and actionable security roadmap.'},
      {title: 'CIO & enterprise IT strategy', tag: 'MAKE TECHNOLOGY WORK', desc: 'Align systems, teams and investment with the business. Lead complex transformation with clarity and control.', bullets: ['Enterprise systems & digital transformation', 'Cloud, hybrid environments & integrations', 'IT portfolios, vendors, budgets & delivery'], detail: 'Turn disconnected systems and competing initiatives into a coherent IT plan. My background includes global enterprise projects, regulatory systems and cross-functional delivery.', output: 'A technology roadmap, delivery priorities and an operating model aligned with your business.'},
      {title: 'CTO & technology leadership', tag: 'BUILD WITH CONFIDENCE', desc: 'Translate strategy into delivery. Bring experienced leadership to your product, architecture and technology teams.', bullets: ['Product vision & technology roadmaps', 'Security-by-design & architecture oversight', 'Team coordination & delivery governance'], detail: 'Leadership for organizations that need a senior technology partner. I connect business requirements, product direction, architecture and execution, coordinating your specialists rather than promising every technical discipline.', output: 'A clear product and technology direction, delivery milestones and accountable team coordination.'}
    ], serviceAction: 'Explore the approach', deliverable: 'WHAT YOU GET', discuss: 'Discuss this service',
    results: ['Years across enterprise & government', 'Maintenance cost savings at ICL', 'Operational efficiency improvement at ICL', 'Languages. One clear conversation.'], resultsNote: 'Career outcomes reported in my CV; results depend on context and scope.',
    expLabel: '02 / A TRACK RECORD, NOT A PROMISE', expTitle: 'Experience where\nthe stakes are real.', expIntro: 'Global industry. Government systems. Enterprise products. A career built at the intersection of technology, people and responsibility.',
    jobs: [
      {date:'2026 — PRESENT',org:'Ministry of Finance · SIGMA',role:'Senior Product Manager',desc:'Leading product and IT initiatives in a complex government environment, integrating security, privacy and regulatory requirements.'},
      {date:'2019 — 2026',org:'ICL · Israel Chemicals',role:'Global IT Systems & Project Manager',desc:'Enterprise systems and IT projects across dozens of sites worldwide. Connecting business, IT, security, legal and compliance teams.',metric:'25% lower maintenance costs · 40% higher operational efficiency'},
      {date:'2017 — 2019',org:'Ministry of Finance',role:'Project Manager & Systems Analyst',desc:'Salesforce and regulatory systems for government and the capital market. Requirements, integrations and delivery in a demanding environment.',metric:'45% improvement in response times'},
      {date:'2012 — 2017',org:'Babylon Enterprise',role:'Senior Product & Project Manager',desc:'Enterprise product strategy and implementations. Working with R&D, QA, System and DBA teams to bring complex solutions into everyday use.'},
      {date:'EARLIER EXPERIENCE',org:'IEC · Bezeq · HOT · IDF / Mamram',role:'Engineering, enterprise IT & military service',desc:'A foundation in development, CRM, systems analysis and IT delivery. IDF service in computing and software development, as described in my CV.'}
    ],
    aboutLabel:'03 / THE PERSON BEHIND THE STRATEGY', aboutTitle:'A business mindset.\nA technical foundation.', aboutText:'I’m Sergey. For more than twenty years, I’ve helped organizations turn complicated technology challenges into structured, workable solutions. I combine enterprise IT and product leadership with education in cybersecurity, forensics and privacy.', aboutText2:'My approach is straightforward: understand the business, identify what matters, bring the right people together and follow through. You get a partner who can speak with both your board and your engineering team.',
    mamram:'MILITARY FOUNDATION', mamramText:'IDF / Mamram computing and software development background. Discipline, systems thinking and responsibility carried into civilian technology leadership.', aboutDisclaimer:'Independent advisory. Military experience does not imply a current affiliation with any government or intelligence agency. The hero scene is illustrative.',
    eduTitle:'Education & professional development', education:[['MBA','Cyber Security & Forensics · Ono Academic College'],['CIO','Executive Program · Technion'],['B.Sc.','Computer Science & Mathematics · Netanya Academic College'],['CSFE · DPO','Cybersecurity, digital forensics & data protection'],['Cyber Protection','Cyber Protection Implementer · Cyber Expert Director']],
    briefLabel:'THE THREAT BRIEF', briefTitle:'Risk does not\nwait for readiness.', briefText:'A pager is a reminder: the time to plan is before the alert. Explore three common situations and the decisions that help organizations respond.', briefKinds:['Identity compromise','Supplier exposure','Service disruption'], briefDetails:[{title:'One compromised account. A much bigger problem.',text:'Illustrative scenario: a phishing message captures an employee’s sign-in details. Without strong authentication and limited privileges, a single account can open access to critical systems.',action:'Start with MFA, least privilege, logging and a tested escalation path.'},{title:'Your security boundary includes your suppliers.',text:'Illustrative scenario: a vendor with access to business data experiences a breach. Unclear ownership and excessive permissions can make it difficult to assess your exposure.',action:'Map third-party access, agree on responsibilities and review supplier risks.'},{title:'Could the business run without this system?',text:'Illustrative scenario: ransomware or a major outage makes a critical service unavailable. Recovery depends on knowing priorities, responsibilities and recovery options in advance.',action:'Map critical services, establish recovery objectives and exercise your continuity plan.'}], briefDisclaimer:'Educational scenarios, not a live threat feed. No incident is being reported on this page.',
    contactLabel:'04 / YOUR NEXT MOVE', contactTitle:'Let’s make your\nnext move a secure one.', contactText:'Need a technology leader, an independent security perspective or help with a complex IT initiative? Let’s start with a conversation.', emailMe:'Email me', callMe:'Call me', email:'Your email', fullName:'Your name', interest:'What can I help with?', interests:['Cybersecurity / CISO advisory','Enterprise IT / CIO strategy','Technology / CTO leadership','A project or another question'], message:'A little about your challenge', send:'Prepare email',openEmail:'Open email app', formNote:'Prepare your message, then open it in your email app. No data is stored on this website.', ready:'Your email draft is ready.', fallback:'If your email app did not open, copy the message or email me directly.', copy:'Copy message', copied:'Copied', error:'Please complete your name, a valid email and your message.', privacy:'Privacy', privacyTitle:'Your privacy, simply explained', privacyText:'This website has no advertising trackers or analytics. Language preference is stored locally in your browser. The contact form does not send or store information on a server; it prepares a message in your email application. Email correspondence is handled by your chosen email provider and the recipient’s email provider.', rights:'© 2026 Sergey Shlomov. All rights reserved.', backTop:'Back to top', independent:'Independent cybersecurity & technology advisory',
    seo:'Sergey Shlomov | Cybersecurity & Technology Leadership'
  },
  ru: {
    name:'Сергей Шломов',nav:['Экспертиза','Опыт','Обо мне','Контакты'],talk:'Обсудим задачу',menu:'Открыть меню',close:'Закрыть',
    eyebrow:'КИБЕРБЕЗОПАСНОСТЬ. ТЕХНОЛОГИИ. ЛИДЕРСТВО.',headline:['Ваш бизнес.', 'Моя миссия.'],accent:'Защита по замыслу.',intro:'Превращаю сложные технологические задачи и киберриски в понятные решения. Корпоративный опыт, стратегический подход и партнёр, которому можно доверять.',cta:'Обсудить вашу защиту',explore:'Моя экспертиза',location:'ИЗРАИЛЬ · МЕЖДУНАРОДНЫЙ ОПЫТ',scroll:'УЗНАТЬ БОЛЬШЕ',scenario:'ЦЕНТР МОНИТОРИНГА / ИНТЕРАКТИВНАЯ СЦЕНА',scenarioNote:'Иллюстрация',hotspots:['Киберзащита','IT-стратегия','Готовность к инцидентам'],pagerLabel:'СООБЩЕНИЕ, КОТОРОЕ СТОИТ ПРОЧИТАТЬ',pager:'YOU MAY BE AT RISK. EXTREMIST & STATE-SPONSORED HACKERS NEVER WAIT. PROTECT WHAT MATTERS.',pagerHint:'Нажмите, чтобы открыть обзор',trust:'ОПЫТ В СЛОЖНЫХ КОРПОРАТИВНЫХ СРЕДАХ',gov:'Минфин Израиля',military:'ЦАХАЛ · MAMRAM',
    expertiseLabel:'01 / ЧЕМ Я МОГУ ПОМОЧЬ',expertiseTitle:'Один партнёр.\nСильнее вся организация.',expertiseIntro:'От решений руководства до технологической инфраструктуры. Практическое управление, которое связывает безопасность, системы и бизнес-результаты.',
    services:[
      {title:'Кибербезопасность и CISO-консалтинг',tag:'ЗАЩИТА ГЛАВНОГО',desc:'Понять риски, построить план защиты и принять решения до того, как это придётся делать во время инцидента.',bullets:['Оценка киберрисков и анализ пробелов','Управление безопасностью, приватностью и рисками поставщиков','Готовность к инцидентам и непрерывность бизнеса'],detail:'Независимый взгляд на состояние защиты и практический план с приоритетами по влиянию на бизнес. Координирую проверки безопасности, работу профильных специалистов и устранение уязвимостей.',output:'Реестр рисков, распределение ответственности и реалистичная дорожная карта защиты.'},
      {title:'CIO и корпоративная IT-стратегия',tag:'ТЕХНОЛОГИИ ДЛЯ БИЗНЕСА',desc:'Согласовать системы, команды и инвестиции с целями компании. Провести сложную трансформацию с ясным планом.',bullets:['Корпоративные системы и цифровая трансформация','Облака, гибридная инфраструктура и интеграции','IT-портфель, поставщики, бюджеты и реализация'],detail:'Помогаю объединить разрозненные системы и проекты в согласованную IT-стратегию. Мой опыт — глобальные корпоративные проекты, государственные системы и межфункциональное управление.',output:'Технологическая дорожная карта, приоритеты реализации и операционная модель под задачи бизнеса.'},
      {title:'CTO и технологическое лидерство',tag:'РАЗВИТИЕ С УВЕРЕННОСТЬЮ',desc:'Превратить стратегию в результат. Привнести опытное руководство в продукт, архитектуру и технологические команды.',bullets:['Продуктовое видение и технологические дорожные карты','Безопасность при проектировании и контроль архитектуры','Координация команд и управление реализацией'],detail:'Старший технологический партнёр для вашей организации. Связываю бизнес-требования, продуктовую стратегию, архитектуру и реализацию, координируя профильных специалистов.',output:'Понятное направление развития, этапы реализации и согласованная ответственность команд.'}
    ],serviceAction:'Подробнее о подходе',deliverable:'ЧТО ВЫ ПОЛУЧИТЕ',discuss:'Обсудить услугу',results:['Лет в корпорациях и госсекторе','Экономии на обслуживании в ICL','Рост операционной эффективности в ICL','Языка. Понятный диалог.'],resultsNote:'Результаты из моего резюме; эффект зависит от контекста и задач проекта.',
    expLabel:'02 / ОПЫТ, А НЕ ОБЕЩАНИЯ',expTitle:'Опыт там, где\nвысока ответственность.',expIntro:'Международная промышленность. Государственные системы. Корпоративные продукты. Карьера на пересечении технологий, людей и ответственности.',
    jobs:[{date:'2026 — СЕЙЧАС',org:'Министерство финансов · SIGMA',role:'Старший менеджер продукта',desc:'Продуктовые и IT-инициативы в сложной государственной среде с учётом безопасности, приватности и требований регуляторов.'},{date:'2019 — 2026',org:'ICL · Israel Chemicals',role:'Руководитель глобальных IT-систем и проектов',desc:'Корпоративные системы и IT-проекты на десятках площадок по всему миру. Взаимодействие бизнеса, IT, безопасности, юридических и комплаенс-команд.',metric:'−25% затрат на обслуживание · +40% эффективности'},{date:'2017 — 2019',org:'Министерство финансов Израиля',role:'Менеджер проектов и системный аналитик',desc:'Salesforce и регуляторные системы для государства и рынка капитала. Требования, интеграции и внедрение в сложной среде.',metric:'Улучшение времени ответа на 45%'},{date:'2012 — 2017',org:'Babylon Enterprise',role:'Старший менеджер продуктов и проектов',desc:'Стратегия корпоративного продукта и внедрения. Работа с R&D, QA, системными администраторами и DBA.'},{date:'РАННИЙ ОПЫТ',org:'IEC · Bezeq · HOT · ЦАХАЛ / Mamram',role:'Разработка, корпоративные IT и военная служба',desc:'Разработка, CRM, системный анализ и IT-проекты. Служба в ЦАХАЛ в сфере вычислительных систем и разработки ПО, согласно резюме.'}],
    aboutLabel:'03 / ЧЕЛОВЕК ЗА СТРАТЕГИЕЙ',aboutTitle:'Мышление бизнеса.\nТехническая основа.',aboutText:'Я Сергей. Более двадцати лет помогаю организациям превращать сложные технологические задачи в структурированные, рабочие решения. Сочетаю опыт управления IT и продуктами с образованием в области кибербезопасности, цифровой криминалистики и приватности.',aboutText2:'Мой подход прост: понять бизнес, определить главное, объединить нужных людей и довести работу до результата. Я говорю на языке руководства и технологических команд.',mamram:'ОСНОВА — ВОЕННАЯ СЛУЖБА',mamramText:'Опыт вычислительных систем и разработки ПО в ЦАХАЛ / Mamram. Дисциплина, системное мышление и ответственность — в гражданском технологическом управлении.',aboutDisclaimer:'Независимый консалтинг. Военный опыт не означает текущей связи с государственными органами или разведслужбами. Главная сцена — иллюстрация.',eduTitle:'Образование и профессиональная подготовка',education:[['MBA','Cyber Security & Forensics · Ono Academic College'],['CIO','Программа для руководителей · Technion'],['B.Sc.','Информатика и математика · Netanya Academic College'],['CSFE · DPO','Кибербезопасность, цифровая криминалистика и защита данных'],['Cyber Protection','Cyber Protection Implementer · Cyber Expert Director']],
    briefLabel:'ОБЗОР УГРОЗ',briefTitle:'Риски не ждут\nвашей готовности.',briefText:'Пейджер напоминает: планировать нужно до сигнала тревоги. Изучите три типичных ситуации и решения, которые помогают подготовиться.',briefKinds:['Компрометация учётной записи','Риски поставщиков','Сбой критического сервиса'],briefDetails:[{title:'Одна учётная запись. Намного больше проблем.',text:'Учебный сценарий: фишинговое сообщение приводит к краже данных для входа. Без надёжной аутентификации и минимальных привилегий одна учётная запись может открыть доступ к критическим системам.',action:'Начните с MFA, минимальных прав, журналирования и проверенного порядка эскалации.'},{title:'Ваша граница безопасности включает поставщиков.',text:'Учебный сценарий: поставщик с доступом к корпоративным данным сталкивается с утечкой. Неясная ответственность и избыточные права усложняют оценку последствий.',action:'Опишите доступ третьих сторон, договоритесь об ответственности и оцените риски поставщиков.'},{title:'Сможет ли бизнес работать без этой системы?',text:'Учебный сценарий: шифровальщик или серьёзный сбой делает критический сервис недоступным. Для восстановления нужно заранее определить приоритеты, роли и варианты восстановления.',action:'Определите критические сервисы, цели восстановления и проверьте план непрерывности.'}],briefDisclaimer:'Учебные сценарии, не мониторинг в реальном времени. На этой странице не сообщается о текущем инциденте.',
    contactLabel:'04 / ВАШ СЛЕДУЮЩИЙ ШАГ',contactTitle:'Пусть следующий шаг\nбудет защищённым.',contactText:'Нужен технологический руководитель, независимая оценка безопасности или помощь со сложным IT-проектом? Начнём с разговора.',emailMe:'Написать мне',callMe:'Позвонить',email:'Ваш email',fullName:'Ваше имя',interest:'Чем я могу помочь?',interests:['Кибербезопасность / CISO-консалтинг','Корпоративные IT / CIO-стратегия','Технологии / CTO-руководство','Проект или другой вопрос'],message:'Кратко о вашей задаче',send:'Подготовить письмо',openEmail:'Открыть почтовое приложение',formNote:'Подготовьте письмо, затем откройте его в почтовом приложении. Сайт не сохраняет ваши данные.',ready:'Черновик письма готов.',fallback:'Если почтовое приложение не открылось, скопируйте сообщение или напишите напрямую.',copy:'Скопировать сообщение',copied:'Скопировано',error:'Укажите имя, корректный email и описание задачи.',privacy:'Приватность',privacyTitle:'О вашей приватности',privacyText:'На сайте нет рекламных трекеров и аналитики. Выбранный язык сохраняется локально в браузере. Контактная форма не отправляет и не сохраняет данные на сервере: она готовит письмо в вашем почтовом приложении. Переписка обрабатывается почтовыми провайдерами отправителя и получателя.',rights:'© 2026 Сергей Шломов. Все права защищены.',backTop:'Наверх',independent:'Независимый консалтинг по кибербезопасности и технологиям',seo:'Сергей Шломов | Кибербезопасность и технологическое лидерство'
  },
  he: hebrewContent,
};

const sceneContent = {
  en: {
    motionPause:'Pause scene', motionPlay:'Resume scene',
    labLabel:'WORKSTATIONS / INFRASTRUCTURE / VALIDATION',labTitle:'Strategy meets\nthe real environment.',labIntro:'Security reaches every workstation, every identity and every critical service. A clear baseline connects leadership decisions with controls your teams can validate.',labAlt:'Photorealistic cybersecurity laboratory with desktop workstations, monitoring screens and server racks.',labTabs:['Workstations','Infrastructure','Readiness'],labAction:'Discuss your security baseline',labNote:'Illustrative laboratory environment, not a photograph of a facility owned or operated by Sergey. Assessments and specialist testing are coordinated to the agreed scope.',
    labDetails:[{heading:'Start where people and systems meet.',text:'Establish an endpoint and identity baseline, define ownership and coordinate verification with your IT and security teams.',checks:['MFA, least privilege and access reviews','Endpoint configuration, patching and logging','Defined owners and tracked remediation']},{heading:'Understand the paths through your environment.',text:'Map critical systems, cloud services and integrations before prioritizing security improvements with the right technical specialists.',checks:['Segmentation and secure configuration','Cloud and third-party access boundaries','Security review and specialist test coordination']},{heading:'Test the plan before the real alert.',text:'Make responsibilities and recovery priorities clear. Use tabletop exercises and specialist validation to identify practical gaps.',checks:['Incident roles and escalation paths','Recovery objectives and backup verification','Follow-up actions with accountable owners']}]
  },
  ru: {
    motionPause:'Пауза сцены',motionPlay:'Продолжить сцену',labLabel:'РАБОЧИЕ СТАНЦИИ / ИНФРАСТРУКТУРА / ПРОВЕРКИ',labTitle:'Стратегия — в реальной\nтехнологической среде.',labIntro:'Защита начинается с рабочих станций, учётных записей и критических сервисов. Понятный базовый уровень связывает решения руководства с контролями, которые команда может проверить.',labAlt:'Фотореалистичная лаборатория киберзащиты: рабочие станции, мониторы и серверные стойки.',labTabs:['Рабочие станции','Инфраструктура','Готовность'],labAction:'Обсудить базовый уровень защиты',labNote:'Иллюстративная лаборатория, а не фотография помещения, принадлежащего Сергею. Оценка и профильные проверки координируются в согласованных границах проекта.',
    labDetails:[{heading:'Начните с точки взаимодействия людей и систем.',text:'Определим требования к рабочим станциям и доступу, распределим ответственность и согласуем проверки с вашими IT- и security-командами.',checks:['MFA, минимальные права и пересмотр доступа','Настройки рабочих станций, обновления и журналы','Ответственные и контроль устранения недостатков']},{heading:'Поймите связи внутри вашей инфраструктуры.',text:'Опишем критические системы, облачные сервисы и интеграции, чтобы вместе с профильными специалистами определить приоритеты защиты.',checks:['Сегментация и безопасная конфигурация','Границы облачного доступа и доступа поставщиков','Координация проверок и тестирования специалистами']},{heading:'Проверьте план до настоящего сигнала тревоги.',text:'Определим роли и приоритеты восстановления. Учебные разборы сценариев и профильные проверки помогут найти практические пробелы.',checks:['Роли при инциденте и порядок эскалации','Цели восстановления и проверка резервных копий','План действий с конкретными ответственными']}]
  },

};
for (const lang of Object.keys(sceneContent)) Object.assign(content[lang], sceneContent[lang]);

for (const lang of Object.keys(content)) Object.assign(content[lang], attackContent[lang], editorial[lang], mailCopy[lang]);
